-- Uses the SQL:2003 identity-column syntax (supported by both H2 2.x and
-- PostgreSQL 10+) so this migration runs unchanged on both dev (H2) and prod
-- (PostgreSQL) - see application-dev/prod.properties.

CREATE TABLE app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_sub      VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    display_name    VARCHAR(255),
    picture_url     VARCHAR(1024),
    created_at      TIMESTAMP NOT NULL,
    last_login_at   TIMESTAMP NOT NULL,
    CONSTRAINT uk_app_user_google_sub UNIQUE (google_sub),
    CONSTRAINT uk_app_user_email UNIQUE (email)
);

CREATE TABLE refresh_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    token_hash  VARCHAR(255) NOT NULL,
    expires_at  TIMESTAMP NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP NOT NULL,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash)
);
CREATE INDEX idx_refresh_token_user ON refresh_token (user_id);

CREATE TABLE track (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    natural_key     VARCHAR(512) NOT NULL,
    external_id     VARCHAR(255) NOT NULL,
    youtube_id      VARCHAR(64),
    title           VARCHAR(512) NOT NULL,
    artist          VARCHAR(512) NOT NULL,
    album           VARCHAR(512),
    album_art       VARCHAR(1024),
    preview_url     VARCHAR(1024),
    duration_ms     BIGINT NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    CONSTRAINT uk_track_natural_key UNIQUE (natural_key)
);

CREATE TABLE playlist (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    liked       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL
);
CREATE INDEX idx_playlist_owner ON playlist (owner_id);

CREATE TABLE playlist_track (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id BIGINT NOT NULL REFERENCES playlist (id) ON DELETE CASCADE,
    track_id    BIGINT NOT NULL REFERENCES track (id),
    position    INT NOT NULL,
    added_at    TIMESTAMP NOT NULL,
    CONSTRAINT uk_playlist_track UNIQUE (playlist_id, track_id)
);
